#!/bin/bash
#
# Install via pip into user install dir
#

PIPCMD="python3 -m pip install -qq --user --upgrade"
ANSIBLECOLDIR=".ansible/collections/ansible_collections/"

echo "Setup IAC"
echo "1. Install dependencies locally"
mkdir -p ~/.config/pip/
cp extra/pip.conf ~/.config/pip/pip.conf
echo "1.1 Install local user PIP, if missing apt install python3-pip"
$PIPCMD pip
echo "1.2 Install from requirements.txt"
$PIPCMD -r requirements.txt
echo "1.3 Reload profile for created .local/bin/ directory"
source ~/.profile
echo "2. Install desired collections"
ansible-galaxy install -r requirements.yml >/dev/null 2>&1
echo "3. Install Finished"
echo "    Review config with: ansible-config view"
echo "    Run the playbook with: ansible-playbook playbook.yml"
echo "    Enjoy!"
echo "    You may want to log out and back in for session environment or just restart"
echo "    Validate by checking to see your local path has libraries. Example:"
echo "    $ du -hs ~/.local/lib/python*"
echo "    497M    /home/iac/.local/lib/python3.11/site-packages/"
ansible --version
