---

collections:
  - name: ansible.posix
  - name: ansible.utils
  - name: ansible.netcommon
  - name: ansible.windows
  - name: community.crypto
  - name: community.general
  - name: community.network
  - name: community.windows
